# Generated by Django 6.1 on 2026-08-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="imgbb_delete_url",
            field=models.URLField(blank=True, verbose_name="ImgBB Delete URL"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="imgbb_display_url",
            field=models.URLField(blank=True, verbose_name="ImgBB Display URL"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="imgbb_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="ImgBB Image ID"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="imgbb_medium_url",
            field=models.URLField(blank=True, verbose_name="ImgBB Medium URL"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="imgbb_thumb_url",
            field=models.URLField(blank=True, verbose_name="ImgBB Thumbnail URL"),
        ),
    ]
