# Generated by Django 6.1 on 2026-08-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_category_imgbb_delete_url_category_imgbb_display_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_upload_counter",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Image Upload Counter"
            ),
        ),
    ]
