# Generated by Django 6.1 on 2026-08-21 20:22

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Session Key"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Order Number",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                (
                    "shipping_address_line_1",
                    models.CharField(max_length=255, verbose_name="Address Line 1"),
                ),
                (
                    "shipping_address_line_2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address Line 2"
                    ),
                ),
                (
                    "shipping_city",
                    models.CharField(max_length=100, verbose_name="City"),
                ),
                (
                    "shipping_state",
                    models.CharField(max_length=100, verbose_name="State"),
                ),
                (
                    "shipping_postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postal Code"
                    ),
                ),
                (
                    "shipping_country",
                    django_countries.fields.CountryField(
                        default="NG", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "billing_same_as_shipping",
                    models.BooleanField(default=True, verbose_name="Same as Shipping"),
                ),
                (
                    "billing_first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Billing First Name"
                    ),
                ),
                (
                    "billing_last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Billing Last Name"
                    ),
                ),
                (
                    "billing_address_line_1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Billing Address Line 1",
                    ),
                ),
                (
                    "billing_address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Billing Address Line 2",
                    ),
                ),
                (
                    "billing_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Billing City"
                    ),
                ),
                (
                    "billing_state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Billing State"
                    ),
                ),
                (
                    "billing_postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Billing Postal Code"
                    ),
                ),
                (
                    "billing_country",
                    django_countries.fields.CountryField(
                        blank=True,
                        default="NG",
                        max_length=2,
                        verbose_name="Billing Country",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("gateway", "Payment Gateway"),
                            ("manual", "Manual Transfer"),
                        ],
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Payment Reference"
                    ),
                ),
                (
                    "payment_verified",
                    models.BooleanField(default=False, verbose_name="Payment Verified"),
                ),
                (
                    "payment_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Payment Verified At"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal"
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Shipping Cost",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Discount",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Tax"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tracking Number"
                    ),
                ),
                (
                    "tracking_url",
                    models.URLField(blank=True, verbose_name="Tracking URL"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmed At"
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Shipped At"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivered At"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelled At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="Product Name"),
                ),
                (
                    "product_sku",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Product SKU"
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, upload_to="orders/", verbose_name="Product Image"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Status History",
                "verbose_name_plural": "Order Status History",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="orders_orde_user_id_0ae59f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "-created_at"], name="orders_orde_status_079368_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="orders_orde_order_n_f3ada5_idx"
            ),
        ),
    ]
