# Generated by Django 6.1 on 2026-08-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                ("is_read", models.BooleanField(default=False, verbose_name="Read")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Fluér de Luné",
                        max_length=100,
                        verbose_name="Site Name",
                    ),
                ),
                (
                    "site_tagline",
                    models.CharField(
                        default="Minimalist Luxury Eyewear",
                        max_length=200,
                        verbose_name="Tagline",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="site/", verbose_name="Logo"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, upload_to="site/", verbose_name="Favicon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="hello@fleurdelune.com",
                        max_length=254,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                ("twitter_url", models.URLField(blank=True, verbose_name="Twitter/X")),
                ("tiktok_url", models.URLField(blank=True, verbose_name="TikTok")),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Format: 2348012345678 (no + or spaces)",
                        max_length=20,
                        verbose_name="WhatsApp Number",
                    ),
                ),
                (
                    "whatsapp_message",
                    models.TextField(
                        blank=True,
                        default="Hi Fluér de Luné, I want to inquire about {product_name}.",
                        verbose_name="WhatsApp Message Template",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.TextField(blank=True, verbose_name="Meta Keywords"),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Google Analytics ID"
                    ),
                ),
                (
                    "facebook_pixel_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Facebook Pixel ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
