# Generated by Django 6.1 on 2026-08-23 00:34

from django.db import migrations


def fix_site(apps, schema_editor):
    """Set the correct site domain and name for production."""
    Site = apps.get_model('sites', 'Site')
    Site.objects.update_or_create(
        id=1,
        defaults={
            'domain': 'fluer-de-lune.onrender.com',
            'name': 'Fluér de Luné',
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RunPython(fix_site, migrations.RunPython.noop),
    ]
