# Generated by Django 6.1 on 2026-08-24 10:09

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_fix_site_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="email",
            field=models.EmailField(
                default=apps.core.models.default_contact_email,
                max_length=254,
                verbose_name="Contact Email",
            ),
        ),
    ]
