# Generated by Django 6.1 on 2026-08-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_sitesettings_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="business_hours",
            field=models.CharField(
                blank=True,
                help_text="e.g. Mon-Sat, 9:00am-6:00pm WAT",
                max_length=200,
                verbose_name="Business Hours",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="response_time",
            field=models.CharField(
                blank=True,
                help_text="e.g. We typically reply within 2 hours",
                max_length=100,
                verbose_name="Response Time",
            ),
        ),
    ]
