# Generated by Django 6.1 on 2026-08-21 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualPaymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=100, verbose_name="Bank Name"),
                ),
                (
                    "account_name",
                    models.CharField(max_length=100, verbose_name="Account Name"),
                ),
                (
                    "account_number",
                    models.CharField(max_length=20, verbose_name="Account Number"),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        help_text="Format: 2348012345678 (no + or spaces)",
                        max_length=20,
                        verbose_name="WhatsApp Number",
                    ),
                ),
                (
                    "whatsapp_message_template",
                    models.TextField(
                        default="Hi Fluér de Luné, I want to pay for order {order_number}. Amount: {amount}. My name: {name}",
                        verbose_name="WhatsApp Message Template",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Additional instructions for manual payment",
                        verbose_name="Instructions",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Manual Payment Info",
                "verbose_name_plural": "Manual Payment Info",
            },
        ),
        migrations.CreateModel(
            name="PaymentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("paystack", "Paystack"),
                            ("flutterwave", "Flutterwave"),
                        ],
                        max_length=20,
                        verbose_name="Gateway",
                    ),
                ),
                ("url", models.URLField(verbose_name="Payment URL")),
                (
                    "reference",
                    models.CharField(max_length=100, verbose_name="Reference"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                ("is_used", models.BooleanField(default=False, verbose_name="Used")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_link",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Link",
                "verbose_name_plural": "Payment Links",
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("paystack", "Paystack"),
                            ("flutterwave", "Flutterwave"),
                        ],
                        max_length=20,
                        verbose_name="Gateway",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Reference"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="NGN", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Gateway Response"
                    ),
                ),
                (
                    "gateway_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Gateway Reference"
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="Customer Email"),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="Customer Name"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid At"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reference"], name="payments_pa_referen_72073c_idx"
                    ),
                    models.Index(
                        fields=["gateway_reference"],
                        name="payments_pa_gateway_3df281_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="payments_pa_status_a2ce56_idx",
                    ),
                ],
            },
        ),
    ]
